name: tindex_mobile
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  internet_connection_checker: ^1.0.0+1
# #Maps
  google_maps_flutter:
#   geolocator:
#   geocoding: 
#   #
#   photo_view: ^0.12.0
#   image_picker:
  google_fonts:
#   flutter_html: ^0.8.2
#   html: ^0.13.3
  fluttertoast:

  intl: ^0.17.0 #For multi language_pickers & date format
#   carousel_slider: ^4.0.0
#   logger:
  dio: ^5.2.1+1
  get_storage:
  get:
  badges: ^2.0.1
#   flutter_rating_bar: ^4.0.0
  # open_file:
#   path_provider:
  awesome_notifications: 
  unicons:
  #form
  flutter_form_builder:
#   form_builder_extra_fields: ^7.0.0
#   form_builder_validators:
  another_flushbar:
#   change_app_package_name:
  sms_autofill:
#   connectivity_plus: ^2.2.0
#   shimmer:
  pocketbase: ^0.5.0+1
  loading_animation_widget:
  getwidget: ^3.0.1
#   flutter_calendar_carousel: ^2.4.1
#   table_calendar: ^3.0.8

#   url_launcher:
#   # universal_html: ^1.2.3
  flutter_svg: ^1.0.3














  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\img\1.png
    - assets/img/full_logo.png
    - assets/img/onBoardingImage.png
    - assets/fonts/
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

